### ISSUE TITLE
Having issues importing data set

### ISSUE THREAD

**Issue by AlessandroPorcelli91** [kmisiunas/mathematica-comsol#1]
First of all thanks for sharing your code! I am trying to use your package to import a dataset from Comsol 5.1 to Mathematica 11.2, I am pretty sure the package has been installed correctly but by writing the following

Needs["COMSOL`"]

Import["filepath", \" COMSOL \"]

 I just get the typical error message: "Import["filepath", cannot be \
followed by "\" COMSOL \"]"

Could you help me out? Thanks again.

**Comment by kmisiunas** [comment]
Hi. i am not maintaining this package since i am not using it anymore. Looking at your import string, do you have spaces around the COMSOL word? this would definitely be a problem, but i suspect this is just a mistake at copy paste. otherwise feel free to have a look inside the code - it is rather simple. good luck!

**Comment by AlessandroPorcelli91** [comment]
Thanks for the swift response! I think I have found out what's going on...there's something strange about character conversion that was screwing me over: the import option reported in the readme features some oddly placed backslashes which I actually put in my message, but I see they disappeared in the published issue...Oddly enough this is probably GitHub's fault, I just got rid of all of them and it is now working fine!

Thanks and have a nice day!
